travis:
  secure:
    BINSTAR_TOKEN: MJ1g7De/vvGPxObQLwQI8bHXFN9+ECCcPxYMihGGqQvgBSm+LUeEARMv1kHtDInepRDEdRO7gXZmM3fTos6Bsi+ynXnOSiU+F5MX3IInp/KvRDI97LsYUwECiB5jgLN136XQpde8IiSpuPDkYmOZZXLdoNWPXyJcToi8DXWDJdYNaywzIQzSClbRcc1/4+zvYsOjTWjyh1odSBDfZVtqLGqpd+KXFfu1OKj90Y6Evy96QneaW+p9IPIwXUZbROSA9qEDjiqbpTuzbeMF6DEk8rhhXCr52Ofx2dWDN6e9iZJLPoqaMu6U2Eqvu/3czBt1YPGd6YgRYoSAZrW4SdNIwW8QvKPq3xh36aKMjTmd6BELJgGt18DGJ2CNdbJBsMHo7qcS6wSWh7Ivqhrf2Q6tXSfAFDypxtyzi4UYClAIPTXYlnexdv+qLsMqWm6s6XWckOp9/9ofol+3M7X84zif1voBY3vniiqrVf6i1yyfGmhXtPp2aA8TzZZHARHo8RVVYR6AgTzATCIO3gjzuPJfSsey2RtkYKUb8XV3bKH0rsvik2jycLRWiAUnfql6gJ7ZbDPQLXYBpAkqL1JQrRrn0UnBQgUO7oKzgzVrjk3nOYcdQPH5axOInkJyvdm5wuMgQNQv3QKJVdxGRXQt9rF95LOZaKM2uGcf26NKC31QRoI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
